spring:
  application:
    name: api-gateway

  ## Gateway configurations
  cloud:
    gateway:
      routes:
        ## user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        ## authentication-service
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka